import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="CS career job resume interview recruitment campus recruit social recruit technical resume project experience STAR method project highlight technical difficulty quantified result GitHub portfolio personal page eight-part essay computer foundation OS network database data structure algorithm system design project interview pressure interview behavioral interview HR interview self-introduction career plan reasons for leaving strengths weaknesses salary expectation offer comparison salary negotiation interview review delivery strategy internal referral job information filtering interview etiquette job hunting route position portrait frontend backend Java Go Python data analysis AI product testing operations embedded internship campus recruit resume screening resume format project packaging technical depth architecture thinking problem-solving ability communication skill teamwork leadership conflict resolution feedback interview simulation mock interview self-assessment";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"ca-tag-"+String(i+1).padStart(3,"0"),name:n,category:"Career",description:"Career标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"ca-course-01",order:1,slug:"CareerMap",title:"计算机求职路线与岗位地图",description:"岗位分类、技能要求、发展路线。",estimatedHours:4,diff:"easy"},
  {id:"ca-course-02",order:2,slug:"RecruitProcess",title:"实习、校招、社招与招聘流程",description:"时间线、流程、投递渠道、内推。",estimatedHours:6,diff:"easy"},
  {id:"ca-course-03",order:3,slug:"ResumeWriting",title:"技术简历结构与内容写法",description:"简历模板、项目描述、技能标签、量化结果。",estimatedHours:10,diff:"medium"},
  {id:"ca-course-04",order:4,slug:"ProjectSTAR",title:"项目经历包装与STAR表达",description:"STAR法则、项目亮点、技术难点、成果量化。",estimatedHours:10,diff:"medium"},
  {id:"ca-course-05",order:5,slug:"CSFundamentals",title:"计算机基础面试准备",description:"OS/网络/数据库/数据结构重点复习。",estimatedHours:12,diff:"medium"},
  {id:"ca-course-06",order:6,slug:"TechStack",title:"编程语言与技术栈面试准备",description:"Java/Go/Python/前端技术栈高频题。",estimatedHours:10,diff:"hard"},
  {id:"ca-course-07",order:7,slug:"Algorithm",title:"算法题面试策略",description:"刷题策略、常见题型、模板、时间空间优化。",estimatedHours:12,diff:"hard"},
  {id:"ca-course-08",order:8,slug:"ProjectInterview",title:"项目面试与架构追问",description:"项目深挖、系统设计追问、难点复盘。",estimatedHours:10,diff:"hard"},
  {id:"ca-course-09",order:9,slug:"HRInterview",title:"行为面试与HR面试",description:"自我介绍、职业规划、离职原因、优缺点、薪资。",estimatedHours:8,diff:"medium"},
  {id:"ca-course-10",order:10,slug:"OnlineTest",title:"笔试、在线测评与群面基础",description:"笔试题型、心理测评、群面角色。",estimatedHours:6,diff:"medium"},
  {id:"ca-course-11",order:11,slug:"Strategy",title:"投递策略、内推与求职节奏",description:"目标公司、投递节奏、内推渠道、招聘信息。",estimatedHours:6,diff:"medium"},
  {id:"ca-course-12",order:12,slug:"ReviewOffer",title:"面试复盘、Offer比较与谈薪入门",description:"复盘方法、Offer维度、谈薪策略、签约注意事项。",estimatedHours:8,diff:"hard"},
  {id:"ca-course-13",order:13,slug:"DirectionCases",title:"不同方向求职案例",description:"前后端/数据/AI/测试/运维/嵌入式案例。",estimatedHours:10,diff:"hard"},
  {id:"ca-course-14",order:14,slug:"PortfolioMock",title:"求职作品集、模拟面试与综合训练",description:"作品集整理、模拟面试、综合训练。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["了解求职流程","能写技术简历","能应对面试","有求职作品集"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"ca-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["Career"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"Career课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["求职路线","职业规划"],["简历","技术简历"],["STAR法则","项目表达"],["面试","技术面试"],["算法题","编程题"],["HR面试","行为面试"],["Offer","薪资谈判"],["项目深挖","技术追问"],["投递策略","求职渠道"],["笔试","在线测评"],["群面","团队协作"],["自我介绍","面试开场"],["职业规划","发展目标"],["复盘","面试总结"],["作品集","求职展示"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"ca-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"Career",tags:["Career"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"ca-kp-"+String(k.length+1).padStart(4,"0"),name:"Career概念"+(k.length+1),description:"Career概念",category:"Career",tags:["Career"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["CareerMap","RecruitProcess","ResumeWriting","ProjectSTAR","CSFundamentals","TechStack","Algorithm","ProjectInterview","HRInterview","OnlineTest","Strategy","ReviewOffer","DirectionCases","PortfolioMock"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"技术简历应该突出什么？",["项目成果和能力","个人兴趣","学校名称","籍贯"],"A","easy"],[1,"校招时间线？",["春招秋招","随时投","看公司","按季度"],"A","easy"],[2,"项目经历采用什么表达？",["STAR法则","时间顺序","流水账","随意"],"A","easy"],[3,"STAR中R代表？",["结果","情境","任务","行动"],"A","medium"],[4,"基础面试常考？",["OS/网络/数据库","社交能力","办公软件","外语"],"A","medium"],[5,"八股文指？",["高频面试题","八个股票","八段文字","八个算法"],"A","medium"],[6,"刷算法题推荐？",["循序渐进","只做难题","只做简单","随机"],"A","medium"],[7,"项目追问考察？",["技术深度和思考","语言能力","长相","学校"],"A","hard"],[8,"HR面试关注？",["综合匹配度","编程能力","算法","设计"],"A","hard"],[10,"Offer比较考虑？",["平台/薪资/成长","只看薪资","只看地点","只看名气"],"A","hard"],[11,"面试复盘重点是？",["查漏补缺","记录过程","抱怨面试官","删掉记录"],"A","hard"],[13,"作品集包含？",["项目亮点和成果","生活照片","成绩单","获奖证书"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"ca-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确答案是"+t_[3]+"。",wrong_reason:"需要加强理解。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:700},{type:"multiple_choice",min:300},{type:"true_false",min:300},{type:"fill_blank",min:300},{type:"short_answer",min:800},{type:"case_analysis",min:1400}];
  while(qid<=3500){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="ca-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s=["关于求职"+ch+"以下正确的是？",""+ch+"的核心要点是？","以下哪个不是"+ch+"的内容？"][~~(Math.random()*3)];o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"}});a="A";}
    else if(it.type==="multiple_choice"){s="求职"+ch+"哪些正确？（多选）";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"}});a="AB";}
    else if(it.type==="true_false"){s=ch+"是求职重要环节。（判断）";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="求职"+ch+"中____是关键环节。";o=[{label:"A",text:"____"}];a="关键环节";}
    else if(it.type==="short_answer"){s="简述"+ch+"在求职中的作用及准备方法。";o=[{label:"A",text:"简答"}];a=ch+"是求职重要环节，需要提前准备。";}
    else if(it.type==="case_analysis"){s="求职"+ch+"案例：分析问题并给出建议。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确答案是"+a+"。掌握"+ch+"对求职至关重要。",wrong_reason:"需要加强相关知识。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"ca-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["前端简历","后端简历","Java简历","Go简历","Python简历","数据分析简历","AI产品简历","测试简历","运维简历","嵌入式简历","项目包装","项目追问","自我介绍","HR面试","算法面试复盘","系统设计面试","实习投递","校招投递","Offer比较","谈薪沟通"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"ca-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握求职技能",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"背景",description:"分析"},{order:2,title:"方案",description:"设计"},{order:3,title:"实现",description:"执行"},{order:4,title:"验证",description:"检查"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"Career路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"ca-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["求职","简历","STAR","面试","算法","HR面","Offer","项目深挖","投递","八股文","笔试","群面","复盘","自我介绍","作品集"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["Career概念"+i,"Career概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"ca-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"Career",tags:["Career"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["求职问题"+(i+1)+"?","求职问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"ca-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"Career",tags:["Career"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["Career"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["Career"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["Career"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["Career"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["Career"]});});return e;}
async function main(){
  console.log("Gen Career...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-cs-career-interview",slug:"module-cs-career-interview",title:"计算机求职简历与面试",subtitle:"面向计算机求职者",description:"面向计算机相关岗位求职者的岗位认知技术简历项目包装八股复习算法面试项目面试HR面试投递策略面试复盘与Offer选择训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["计算机求职","技术简历","面试","校招","实习","项目包装","算法面试","HR面试"],estimatedHours:150,difficulty:"intermediate",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F4BC}",repoUrl:"https://github.com/openskill-galaxy/module-cs-career-interview",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
